all: c cpp linkcpp run
nall: null run

cpp:
	g++ -c ./src/*.cpp -Iincludes
	
c:
	gcc -c ./src/*.c -Iincludes

linkc:
	gcc *.o -o ./bin/main.exe -lgdi32

linkcpp:
	g++.exe *.o -o ./bin/main.exe -lgdi32
	
run:
	./bin/main.exe 

clean:
	rm -f *.o

#-mwindows
 